[package]
name = "exploit_proj"
version = "0.1.0"
edition = "2021"

[build-dependencies]
exploit = { path = "exploit", artifact = "bin", target = "x86_64-unknown-linux-musl" }
#exploit = { path = "exploit", artifact = "bin", target = "x86_64-unknown-linux-gnu" }

[workspace]
resolver = "2"

members = [
  "exploit"
]

